/*
 * timer1_types.h
 *
 * Created: 3/8/2023 10:41:51 AM
 *  Author: basem
 */ 


#ifndef TIMER1_TYPES_H_
#define TIMER1_TYPES_H_

typedef enum
{
	TIMER1_NORMAL_MODE,
	TIMER1_FASTPWM_ICR1_TOP_MODE,
	TIMER1_FASTPWM_OCRA_TOP_MODE
	/*TIMER1_PHASE_CORRECT_MODE,
	TIMER1_CTC_MODE,
	TIMER1_FAST_PWM_MODE*/
}timer1_mode_t;

typedef enum
{
	TIMER1_STOP = 0,
	TIMER1_PRESCALLER_1,
	TIMER1_PRESCALLER_8,
	TIMER1_PRESCALLER_64,
	TIMER1_PRESCALLER_256,
	TIMER1_PRESCALLER_1024,
	TIMER1_FALLING_EDGE,
	TIMER1_RISING_EDGE
}timer1_prescaller_t;


typedef enum
{
	OCRA_DISCONNECTED=0,
	OCRA_TOGGLE,
	OCRA_NON_INVERTING,
	OCRA_INVERTING
}OCRA_mode_t;

typedef enum
{
	OCRB_DISCONNECTED=0,
	OCRB_TOGGLE,
	OCRB_NON_INVERTING,
	OCRB_INVERTING
}OCRB_mode_t;

typedef enum
{
	ICU_FALLING_EDGE,
	ICU_RISING_EDGE
	}ICU_mode_t;
#endif /* TIMER1_TYPES_H_ */